name: devcontainerイメージ自動ビルド・起動テスト呼び出し

on:
  push:
    branches: [main]
    paths:
      - 'devcontainers/**'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - 'devcontainers/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/devcontainer-image-build.yml
    secrets: inherit # 必要なら
    with:
      search_path: devcontainers

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: 通知・結果出力
        run: |
          RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          if [ "${{ needs.build.result }}" = "success" ]; then
            echo "✅ 成功: $RUN_URL"
          else
            echo "❌ 失敗: $RUN_URL"
            exit 1
          fi