name: ShellCheck(PR)

on:
  pull_request:
    paths:
      - '**/*.sh'
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - unlocked
      - review_requested
      - milestoned
      - demilestoned

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          level: warning
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review